# --- FONT ---
font_family      Monocraft
font_size        12.0
bold_font        auto
italic_font      auto
bold_italic_font auto

# --- PENCERE VE SAYDAMLIK ---
# 0.85 arka planı hafif saydam yapar; arkadaki yeşil duvar kağıdı hoş görünür
background_opacity 0.85
window_padding_width 12

# İmleç stili (Piksel hissiyatı için blok imleç harika durur)
cursor_shape block
shell_integration no-cursor

# Arka plan en koyu renk (#092328)
background #092328
# Standart yazı rengi en açık adaçayı tonu (#8BBB92)
foreground #8BBB92

# İmleç (Açık yeşil blok imleç)
cursor            #8BBB92
cursor_text_color #092328

# Pencere kenarları ve seçim renkleri
selection_background #2A835F
selection_foreground #092328


# RAM'de tutulan satır geçmişini sınırla (varsayılan 2000 satır fazlasıyla yeterlidir)
scrollback_lines 2000

# Bellekte tutulacak maksimum scrollback boyutu (MB)
scrollback_pager_history_size 8

# Doku ve glif önbelleğini RAM'de şişirmesini engelle
touch_scroll_multiplier 1.0
repaint_delay 10
input_delay 3
sync_to_monitor yes

# Bellek sızıntısı yapabilecek gereksiz özellikleri kapat
enable_audio_bell no
allow_remote_control no

# Yazı tipi ve glif önbelleğini sınırla
box_drawing_scale 0.001, 1, 1.5, 2

# Pencere arka plan bulanıklığını kapat (GPU doku belleğini en çok şişiren şeydir)
background_blur 0


# Fazladan GPU buffer ayrılmasını engelle
wayland_enable_ime no
